-- =============================================================================
-- Migration 289 — Employee Dependents Module
--
-- TABLES
-- ──────
--   employee_dependents             — Effective-dated dependent records per employee.
--                                     Active record = is_active=true AND effective_to='9999-12-31'.
--                                     All versions of the same dependent share a dependent_code.
--   employee_dependent_attachments  — Supporting documents for dependent records.
--                                     Path: dependents/{employee_id}/{dependent_code}/{file}
--
-- FUNCTIONS
-- ─────────
--   fn_generate_dependent_code()— BEFORE INSERT trigger to auto-generate dependent_code.
--   get_employee_dependents()   — Fetch dependents for an employee (active or full history).
--   upsert_dependent()          — Add new dependent or amend existing (effective-dated).
--   remove_dependent()          — Soft-delete (terminate) an active dependent.
--
-- PICKLISTS
-- ─────────
--   DEPENDENT_RELATIONSHIP_TYPE — DR001..DR008 (Spouse, Child, Parent, etc.)
--   DEPENDENT_DOCUMENT_TYPE     — DD001..DD007 (Birth Certificate, etc.)
--
-- PERMISSIONS
-- ───────────
--   dependents.view    sort 140
--   dependents.create  sort 141
--   dependents.edit    sort 142
--   dependents.delete  sort 143
--
-- MODULE CODE
-- ───────────
--   profile_dependents — 'Profile – Dependents'
--
-- DESIGN NOTES
-- ────────────
--   Effective dating: driven by effective_from / effective_to plus is_active flag.
--   The is_active=false + effective_to='9999-12-31' row is the terminal record
--   (removal row) — it closes out the dependent's timeline on removal.
--   Partial unique index uix_dependent_code_active enforces one open-ended row
--   per dependent_code at any time (active or terminated).
--   dependent_code format: {employee_id}_DEP_{NN} e.g. EMP1001_DEP_01.
--   Gender stored as plain text 'Male' | 'Female' (not picklist).
-- =============================================================================


-- NOTE: Audit infrastructure (employee_audit_log table + trg_write_audit_log()
-- trigger function) already exists from Migration 100. No need to recreate here.


-- =============================================================================
-- Part 3 — Picklists: DEPENDENT_RELATIONSHIP_TYPE and DEPENDENT_DOCUMENT_TYPE
-- =============================================================================

-- ── DEPENDENT_RELATIONSHIP_TYPE ───────────────────────────────────────────────

INSERT INTO picklists (picklist_id, name, system, meta_fields)
VALUES (
  'DEPENDENT_RELATIONSHIP_TYPE',
  'Dependent Relationship Type',
  true,
  '[]'::jsonb
)
ON CONFLICT (picklist_id) DO NOTHING;

-- Seed relationship type values (guard with NOT EXISTS on ref_id)
INSERT INTO picklist_values (picklist_id, value, ref_id, active)
SELECT
  (SELECT id FROM picklists WHERE picklist_id = 'DEPENDENT_RELATIONSHIP_TYPE'),
  v.value,
  v.ref_id,
  true
FROM (VALUES
  ('DR001', 'Spouse'),
  ('DR002', 'Child'),
  ('DR003', 'Parent'),
  ('DR004', 'Sibling'),
  ('DR005', 'Step-Child'),
  ('DR006', 'Domestic Partner'),
  ('DR007', 'Ward'),
  ('DR008', 'Other')
) AS v(ref_id, value)
WHERE NOT EXISTS (
  SELECT 1
  FROM   picklist_values pv2
  JOIN   picklists pl2 ON pl2.id = pv2.picklist_id
  WHERE  pl2.picklist_id = 'DEPENDENT_RELATIONSHIP_TYPE'
    AND  pv2.ref_id = v.ref_id
);

-- ── DEPENDENT_DOCUMENT_TYPE ───────────────────────────────────────────────────

INSERT INTO picklists (picklist_id, name, system, meta_fields)
VALUES (
  'DEPENDENT_DOCUMENT_TYPE',
  'Dependent Document Type',
  true,
  '[]'::jsonb
)
ON CONFLICT (picklist_id) DO NOTHING;

-- Seed document type values (guard with NOT EXISTS on ref_id)
INSERT INTO picklist_values (picklist_id, value, ref_id, active)
SELECT
  (SELECT id FROM picklists WHERE picklist_id = 'DEPENDENT_DOCUMENT_TYPE'),
  v.value,
  v.ref_id,
  true
FROM (VALUES
  ('DD001', 'Birth Certificate'),
  ('DD002', 'Marriage Certificate'),
  ('DD003', 'Passport Copy'),
  ('DD004', 'National ID Copy'),
  ('DD005', 'Insurance Proof'),
  ('DD006', 'Adoption Certificate'),
  ('DD007', 'Other')
) AS v(ref_id, value)
WHERE NOT EXISTS (
  SELECT 1
  FROM   picklist_values pv2
  JOIN   picklists pl2 ON pl2.id = pv2.picklist_id
  WHERE  pl2.picklist_id = 'DEPENDENT_DOCUMENT_TYPE'
    AND  pv2.ref_id = v.ref_id
);


-- =============================================================================
-- Part 4 — employee_dependents table
-- =============================================================================

CREATE TABLE employee_dependents (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  dependent_code      TEXT        NOT NULL,           -- e.g. EMP1001_DEP_01, generated by trigger
  employee_id         UUID        NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  relationship_type   TEXT        NOT NULL,           -- ref_id from DEPENDENT_RELATIONSHIP_TYPE
  dependent_name      TEXT        NOT NULL,
  date_of_birth       DATE        NOT NULL,
  gender              TEXT        NOT NULL,           -- 'Male' | 'Female'
  insurance_eligible  BOOLEAN     NOT NULL DEFAULT false,
  effective_from      DATE        NOT NULL,
  effective_to        DATE        NOT NULL DEFAULT '9999-12-31',
  is_active           BOOLEAN     NOT NULL DEFAULT true,
  inactive_at         TIMESTAMPTZ,
  inactive_by         UUID        REFERENCES profiles(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by          UUID        NOT NULL REFERENCES profiles(id),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by          UUID        NOT NULL REFERENCES profiles(id),

  CONSTRAINT chk_dep_effective_order   CHECK (effective_to >= effective_from),
  CONSTRAINT chk_dep_dob_not_future    CHECK (date_of_birth <= CURRENT_DATE),
  CONSTRAINT chk_dep_name_not_blank    CHECK (length(trim(dependent_name)) > 0),
  CONSTRAINT chk_dep_gender_valid      CHECK (gender IN ('Male','Female'))
);

COMMENT ON TABLE employee_dependents IS
  'Effective-dated dependent records for employees. '
  'Active record = is_active=true AND effective_to=''9999-12-31''. '
  'All versions (history + active) of the same dependent share a dependent_code. '
  'Terminal (removal) record = is_active=false AND effective_to=''9999-12-31''. '
  'dependent_code format: {employee_code}_DEP_{NN} e.g. EMP1001_DEP_01. '
  'Gender stored as plain text ''Male'' | ''Female''. '
  'Partial unique index uix_dependent_code_active enforces one open-ended row per dependent_code. '
  'Mig 289: initial creation.';

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Fast employee lookups (primary query pattern)
CREATE INDEX idx_dependents_employee
  ON employee_dependents(employee_id);

-- Lookup by dependent_code (amendment, removal, attachment join)
CREATE INDEX idx_dependents_code
  ON employee_dependents(dependent_code);

-- Active dependents per employee (most frequent query pattern)
CREATE INDEX idx_dependents_active
  ON employee_dependents(employee_id, is_active)
  WHERE is_active = true AND effective_to = '9999-12-31';

-- Timeline queries (history view ordered by period)
CREATE INDEX idx_dependents_timeline
  ON employee_dependents(dependent_code, effective_from, effective_to);

-- ── Partial unique index ──────────────────────────────────────────────────────

-- Enforces exactly one open-ended row per dependent_code at any time.
-- Whether the open-ended row is active (is_active=true) or terminal (is_active=false),
-- there can only ever be one row with effective_to='9999-12-31' per dependent_code.
CREATE UNIQUE INDEX uix_dependent_code_active
  ON employee_dependents(dependent_code)
  WHERE effective_to = '9999-12-31';


-- =============================================================================
-- Part 5 — fn_generate_dependent_code() trigger function + triggers
-- =============================================================================

CREATE OR REPLACE FUNCTION fn_generate_dependent_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_emp_code TEXT;
  v_seq      INT;
BEGIN
  IF TG_OP = 'INSERT' AND (NEW.dependent_code IS NULL OR NEW.dependent_code = '') THEN
    -- Advisory lock per employee to prevent race conditions on concurrent inserts
    PERFORM pg_advisory_xact_lock(hashtext(NEW.employee_id::TEXT));

    -- Get the employee's code (stored as employee_id column in employees table)
    SELECT employee_id INTO v_emp_code
    FROM employees
    WHERE id = NEW.employee_id;

    -- Determine next sequence number across ALL rows for this employee
    -- (active + historical + terminal, so codes never collide)
    SELECT COALESCE(MAX(
      (regexp_match(dependent_code, '_DEP_(\d+)$'))[1]::INT
    ), 0) + 1
    INTO v_seq
    FROM employee_dependents
    WHERE employee_id = NEW.employee_id;

    NEW.dependent_code := v_emp_code || '_DEP_' || LPAD(v_seq::TEXT, 2, '0');
  END IF;
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_generate_dependent_code() IS
  'BEFORE INSERT trigger on employee_dependents. '
  'Auto-generates dependent_code = {employee_code}_DEP_{NN} when not supplied. '
  'Uses pg_advisory_xact_lock to prevent duplicate codes under concurrent inserts. '
  'Mig 289: initial creation.';

-- Apply code-generation trigger (BEFORE INSERT)
CREATE TRIGGER trg_dependent_code_generate
  BEFORE INSERT ON employee_dependents
  FOR EACH ROW EXECUTE FUNCTION fn_generate_dependent_code();

-- Apply updated_at maintenance trigger (BEFORE UPDATE)
CREATE TRIGGER trg_employee_dependents_updated_at
  BEFORE UPDATE ON employee_dependents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Apply audit trigger (AFTER INSERT/UPDATE/DELETE)
CREATE TRIGGER trg_employee_dependents_audit
  AFTER INSERT OR UPDATE OR DELETE ON employee_dependents
  FOR EACH ROW EXECUTE FUNCTION trg_write_audit_log();


-- =============================================================================
-- Part 6 — employee_dependent_attachments table
-- =============================================================================

CREATE TABLE employee_dependent_attachments (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  dependent_code      TEXT        NOT NULL,           -- logical dependent identity (not FK enforced)
  employee_id         UUID        NOT NULL REFERENCES employees(id),
  dependent_id        UUID        REFERENCES employee_dependents(id),  -- version context, nullable
  document_type       TEXT,                           -- ref_id from DEPENDENT_DOCUMENT_TYPE
  file_name           TEXT        NOT NULL,           -- sanitized storage filename
  original_file_name  TEXT        NOT NULL,           -- user's original filename
  file_path           TEXT        NOT NULL,           -- storage path: dependents/{emp_id}/{dep_code}/{file}
  mime_type           TEXT        NOT NULL,
  file_size           BIGINT      NOT NULL CHECK (file_size > 0),
  is_active           BOOLEAN     NOT NULL DEFAULT true,
  uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  uploaded_by         UUID        NOT NULL REFERENCES profiles(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by          UUID        NOT NULL REFERENCES profiles(id),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by          UUID        NOT NULL REFERENCES profiles(id)
);

COMMENT ON TABLE employee_dependent_attachments IS
  'Supporting documents for employee dependent records. '
  'Linked by dependent_code (logical identity) rather than dependent_id (version) '
  'so attachments persist across effective-dated amendments. '
  'dependent_id (nullable) records which version row triggered the upload. '
  'Stored in hr-attachments bucket at dependents/{employee_id}/{dependent_code}/{filename}. '
  'is_active=false soft-deletes without removing the storage file. '
  'Mig 289: initial creation.';

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Primary query: attachments for a specific dependent of a specific employee
CREATE INDEX idx_dep_attachments_code
  ON employee_dependent_attachments(dependent_code, employee_id);

-- Employee-level attachment queries
CREATE INDEX idx_dep_attachments_employee
  ON employee_dependent_attachments(employee_id);

-- Active attachments per dependent (most common query pattern)
CREATE INDEX idx_dep_attachments_active
  ON employee_dependent_attachments(dependent_code)
  WHERE is_active = true;

-- Version-context lookup (nullable, so partial index)
CREATE INDEX idx_dep_attachments_dep_id
  ON employee_dependent_attachments(dependent_id)
  WHERE dependent_id IS NOT NULL;

-- Apply updated_at maintenance trigger (BEFORE UPDATE)
CREATE TRIGGER trg_employee_dependent_attachments_updated_at
  BEFORE UPDATE ON employee_dependent_attachments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Apply audit trigger (AFTER INSERT/UPDATE/DELETE)
CREATE TRIGGER trg_employee_dependent_attachments_audit
  AFTER INSERT OR UPDATE OR DELETE ON employee_dependent_attachments
  FOR EACH ROW EXECUTE FUNCTION trg_write_audit_log();


-- =============================================================================
-- Part 7 — RLS on employee_dependents
-- =============================================================================

ALTER TABLE employee_dependents ENABLE ROW LEVEL SECURITY;

-- SELECT: HR/admin with view or edit permission, OR employee viewing their own dependents
CREATE POLICY ed_select ON employee_dependents FOR SELECT
  USING (
    user_can('dependents', 'view', employee_id)
    OR user_can('dependents', 'edit', employee_id)
    OR (
      employee_id = get_my_employee_id()
      AND has_permission('dependents.view')
    )
  );

-- INSERT: HR/admin with create permission, OR employee creating their own dependent
CREATE POLICY ed_insert ON employee_dependents FOR INSERT
  WITH CHECK (
    user_can('dependents', 'create', employee_id)
    OR (
      employee_id = get_my_employee_id()
      AND has_permission('dependents.create')
    )
  );

-- UPDATE: HR/admin with edit permission, OR employee editing their own dependent
-- UPDATE is also needed for the effective_to close-out during amendments
CREATE POLICY ed_update ON employee_dependents FOR UPDATE
  USING (
    user_can('dependents', 'edit', employee_id)
    OR (
      employee_id = get_my_employee_id()
      AND has_permission('dependents.edit')
    )
  );

-- DELETE: HR/admin only — employees must use remove_dependent() RPC (soft-delete)
CREATE POLICY ed_delete ON employee_dependents FOR DELETE
  USING (
    user_can('dependents', 'delete', employee_id)
  );


-- =============================================================================
-- Part 8 — RLS on employee_dependent_attachments
-- =============================================================================

ALTER TABLE employee_dependent_attachments ENABLE ROW LEVEL SECURITY;

-- SELECT: mirrors the dependent policy
CREATE POLICY eda_select ON employee_dependent_attachments FOR SELECT
  USING (
    user_can('dependents', 'view', employee_id)
    OR user_can('dependents', 'edit', employee_id)
    OR (
      employee_id = get_my_employee_id()
      AND has_permission('dependents.view')
    )
  );

-- INSERT: HR/admin with edit permission, OR employee managing their own attachments
CREATE POLICY eda_insert ON employee_dependent_attachments FOR INSERT
  WITH CHECK (
    user_can('dependents', 'edit', employee_id)
    OR (
      employee_id = get_my_employee_id()
      AND has_permission('dependents.edit')
    )
  );

-- UPDATE (soft-delete via is_active): same as INSERT
CREATE POLICY eda_update ON employee_dependent_attachments FOR UPDATE
  USING (
    user_can('dependents', 'edit', employee_id)
    OR (
      employee_id = get_my_employee_id()
      AND has_permission('dependents.edit')
    )
  );

-- Hard delete: HR/admin only
CREATE POLICY eda_delete ON employee_dependent_attachments FOR DELETE
  USING (
    user_can('dependents', 'delete', employee_id)
  );


-- =============================================================================
-- Part 9 — Permission seeds
-- =============================================================================

INSERT INTO permissions (code, name, description, module_id, sort_order)
SELECT p.code, p.name, p.description, m.id, p.sort_order
FROM (VALUES
  ('dependents.view',
   'View Dependents',
   'View dependent records for employees in your target group.',
   140),
  ('dependents.create',
   'Add Dependents',
   'Add new dependent records for employees in your target group.',
   141),
  ('dependents.edit',
   'Edit Dependents',
   'Edit and amend dependent records for employees in your target group.',
   142),
  ('dependents.delete',
   'Remove Dependents',
   'Remove (terminate) dependent records for employees in your target group.',
   143)
) AS p(code, name, description, sort_order)
JOIN modules m ON m.code = 'employee'
ON CONFLICT (code) DO UPDATE
  SET name        = EXCLUDED.name,
      description = EXCLUDED.description,
      sort_order  = EXCLUDED.sort_order,
      module_id   = EXCLUDED.module_id;


-- =============================================================================
-- Part 10 — Module code
-- =============================================================================

INSERT INTO module_codes (code, label, description)
VALUES (
  'profile_dependents',
  'Profile – Dependents',
  'Employee dependent add / edit / remove requests requiring approval'
)
ON CONFLICT (code) DO NOTHING;


-- =============================================================================
-- Part 11 — get_employee_dependents RPC
-- =============================================================================

CREATE OR REPLACE FUNCTION get_employee_dependents(
  p_employee_id      uuid,
  p_include_history  boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  -- ── Access guard ──────────────────────────────────────────────────────────
  -- Four access paths:
  --   a) HR/admin with dependents.view permission scoped to employee's target group
  --   b) HR/admin with dependents.edit permission (can view as part of edit access)
  --   c) Employee viewing their own dependents with ESS dependents.view permission
  --   d) Approver holding a pending workflow task for this employee
  --   e) Initiator whose submission was sent back for clarification
  IF NOT (
    user_can('dependents', 'view', p_employee_id)
    OR user_can('dependents', 'edit', p_employee_id)
    OR (
      p_employee_id = get_my_employee_id()
      AND has_permission('dependents.view')
    )
    OR EXISTS (
      SELECT 1
      FROM   workflow_tasks wt
      JOIN   workflow_instances wi ON wi.id = wt.instance_id
      WHERE  wi.record_id   = p_employee_id
        AND  wt.assigned_to = auth.uid()
        AND  wt.status      = 'pending'
    )
    OR EXISTS (
      SELECT 1
      FROM   workflow_instances wi
      WHERE  wi.record_id    = p_employee_id
        AND  wi.submitted_by = auth.uid()
        AND  wi.status       = 'awaiting_clarification'
    )
  ) THEN
    RETURN '[]'::jsonb;
  END IF;

  -- ── Query ──────────────────────────────────────────────────────────────────
  SELECT jsonb_agg(
    jsonb_build_object(
      'id',                  d.id,
      'dependent_code',      d.dependent_code,
      'employee_id',         d.employee_id,
      'relationship_type',   d.relationship_type,
      'dependent_name',      d.dependent_name,
      'date_of_birth',       d.date_of_birth,
      'gender',              d.gender,
      'insurance_eligible',  d.insurance_eligible,
      'effective_from',      d.effective_from,
      'effective_to',        d.effective_to,
      'is_active',           d.is_active,
      'inactive_at',         d.inactive_at,
      'inactive_by',         d.inactive_by,
      'created_at',          d.created_at,
      'created_by',          d.created_by,
      'updated_at',          d.updated_at,
      'updated_by',          d.updated_by,
      'attachments', COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
          'id',                 att.id,
          'document_type',      att.document_type,
          'file_name',          att.file_name,
          'original_file_name', att.original_file_name,
          'file_path',          att.file_path,
          'mime_type',          att.mime_type,
          'file_size',          att.file_size,
          'uploaded_at',        att.uploaded_at
        ) ORDER BY att.uploaded_at)
        FROM employee_dependent_attachments att
        WHERE att.dependent_code = d.dependent_code
          AND att.employee_id    = d.employee_id
          AND att.is_active      = true),
        '[]'::jsonb
      )
    )
    ORDER BY d.dependent_code, d.effective_from DESC
  )
  INTO v_result
  FROM employee_dependents d
  WHERE d.employee_id = p_employee_id
    AND (
      p_include_history = true
      OR (d.is_active = true AND d.effective_to = '9999-12-31'::date)
    );

  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;

COMMENT ON FUNCTION get_employee_dependents(uuid, boolean) IS
  'Returns dependent records for an employee. '
  'Pass p_include_history=true for full effective-dated history including removed dependents. '
  'Default (p_include_history=false) returns only currently active open-ended rows. '
  'Each record includes its active attachments. '
  'Access-guarded: caller must have view or edit dependents permission scoped to the employee, '
  'or be the employee themselves, or hold a pending workflow task, or be the initiator of a sent-back submission. '
  'Returns []::jsonb (not an error) when access is denied. '
  'Mig 289: initial creation.';

REVOKE ALL     ON FUNCTION get_employee_dependents(uuid, boolean) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION get_employee_dependents(uuid, boolean) TO authenticated;


-- =============================================================================
-- Part 12 — upsert_dependent RPC
-- =============================================================================

CREATE OR REPLACE FUNCTION upsert_dependent(
  -- Required params first (no defaults)
  p_employee_id        uuid,
  p_relationship_type  text,
  p_dependent_name     text,
  p_date_of_birth      date,
  p_gender             text,
  p_effective_from     date,
  -- Optional params with defaults
  p_dependent_code     text    DEFAULT NULL,    -- NULL = new dependent
  p_insurance_eligible boolean DEFAULT false,
  p_is_new_hire        boolean DEFAULT false,
  p_attachments        jsonb   DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_dependent_id    uuid;
  v_dependent_code  text;
  v_current_row     employee_dependents%ROWTYPE;
  v_att             jsonb;
  v_name            text;
BEGIN
  -- ── 1. Access guard ────────────────────────────────────────────────────────
  -- Four paths:
  --   a) HR/admin: check 'create' for new dependent, 'edit' for amendment
  --   b) ESS self: same permission split
  --   c) Approver holding a pending workflow task for this employee
  --   d) Initiator whose submission was sent back for clarification
  IF p_dependent_code IS NULL THEN
    -- New dependent: require 'create' permission
    IF NOT (
      user_can('dependents', 'create', p_employee_id)
      OR (
        p_employee_id = get_my_employee_id()
        AND has_permission('dependents.create')
      )
      OR EXISTS (
        SELECT 1
        FROM   workflow_tasks wt
        JOIN   workflow_instances wi ON wi.id = wt.instance_id
        WHERE  wi.record_id   = p_employee_id
          AND  wt.assigned_to = auth.uid()
          AND  wt.status      = 'pending'
      )
      OR EXISTS (
        SELECT 1
        FROM   workflow_instances wi
        WHERE  wi.record_id    = p_employee_id
          AND  wi.submitted_by = auth.uid()
          AND  wi.status       = 'awaiting_clarification'
      )
    ) THEN
      RETURN jsonb_build_object('ok', false, 'error', 'Access denied: you do not have permission to add dependents for this employee.');
    END IF;
  ELSE
    -- Amendment: require 'edit' permission
    IF NOT (
      user_can('dependents', 'edit', p_employee_id)
      OR (
        p_employee_id = get_my_employee_id()
        AND has_permission('dependents.edit')
      )
      OR EXISTS (
        SELECT 1
        FROM   workflow_tasks wt
        JOIN   workflow_instances wi ON wi.id = wt.instance_id
        WHERE  wi.record_id   = p_employee_id
          AND  wt.assigned_to = auth.uid()
          AND  wt.status      = 'pending'
      )
      OR EXISTS (
        SELECT 1
        FROM   workflow_instances wi
        WHERE  wi.record_id    = p_employee_id
          AND  wi.submitted_by = auth.uid()
          AND  wi.status       = 'awaiting_clarification'
      )
    ) THEN
      RETURN jsonb_build_object('ok', false, 'error', 'Access denied: you do not have permission to edit dependents for this employee.');
    END IF;
  END IF;

  -- ── 2. Input validation ───────────────────────────────────────────────────
  -- Trim and validate dependent name
  v_name := trim(p_dependent_name);
  IF v_name IS NULL OR length(v_name) = 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Dependent name is required and must not be blank.');
  END IF;

  -- Date of birth must not be in the future
  IF p_date_of_birth IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Date of birth is required.');
  END IF;
  IF p_date_of_birth > CURRENT_DATE THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Date of birth cannot be in the future.');
  END IF;

  -- Gender must be Male or Female
  IF p_gender IS NULL OR p_gender NOT IN ('Male', 'Female') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Gender must be ''Male'' or ''Female''.');
  END IF;

  -- Effective from is required
  IF p_effective_from IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Effective from date is required.');
  END IF;

  -- Relationship type is required
  IF p_relationship_type IS NULL OR trim(p_relationship_type) = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Relationship type is required.');
  END IF;

  -- ── 3. Amendment path: close or replace the current open-ended row ─────────
  IF p_dependent_code IS NOT NULL THEN

    -- Pre-check: no overlap with existing closed historical rows
    -- A historical row has is_active=true AND effective_to < '9999-12-31'
    -- If such a row's effective_to >= p_effective_from, the new row would overlap it
    IF EXISTS (
      SELECT 1
      FROM   employee_dependents
      WHERE  dependent_code = p_dependent_code
        AND  employee_id    = p_employee_id
        AND  is_active      = true
        AND  effective_to   < '9999-12-31'::date
        AND  effective_to   >= p_effective_from
    ) THEN
      RETURN jsonb_build_object(
        'ok', false,
        'error', 'The chosen effective date overlaps with an existing historical record.'
      );
    END IF;

    -- Fetch the current open-ended row for this dependent
    SELECT * INTO v_current_row
    FROM   employee_dependents
    WHERE  dependent_code = p_dependent_code
      AND  employee_id    = p_employee_id
      AND  effective_to   = '9999-12-31'::date
    FOR UPDATE;

    IF FOUND THEN
      -- Migration 288 pattern:
      -- If the existing row's effective_from >= p_effective_from, the new record
      -- fully replaces the old one (closing it would violate the effective order constraint).
      -- DELETE the old row instead of trying to close it with an impossible date range.
      IF v_current_row.effective_from >= p_effective_from THEN
        DELETE FROM employee_dependents
        WHERE id = v_current_row.id;
      ELSE
        -- Standard close: set effective_to = p_effective_from - 1 day
        UPDATE employee_dependents
        SET    effective_to = p_effective_from - interval '1 day',
               updated_by   = auth.uid(),
               updated_at   = now()
        WHERE  id = v_current_row.id;
      END IF;
    END IF;

  END IF;

  -- ── 4. Insert new row ──────────────────────────────────────────────────────
  INSERT INTO employee_dependents (
    dependent_code,
    employee_id,
    relationship_type,
    dependent_name,
    date_of_birth,
    gender,
    insurance_eligible,
    effective_from,
    effective_to,
    is_active,
    created_by,
    updated_by
  ) VALUES (
    p_dependent_code,        -- NULL lets fn_generate_dependent_code() auto-generate
    p_employee_id,
    p_relationship_type,
    v_name,
    p_date_of_birth,
    p_gender,
    p_insurance_eligible,
    p_effective_from,
    '9999-12-31'::date,
    true,
    auth.uid(),
    auth.uid()
  )
  RETURNING id INTO v_dependent_id;

  -- Fetch the generated (or supplied) dependent_code
  SELECT dependent_code INTO v_dependent_code
  FROM   employee_dependents
  WHERE  id = v_dependent_id;

  -- ── 5. Save attachments ────────────────────────────────────────────────────
  FOR v_att IN SELECT * FROM jsonb_array_elements(p_attachments)
  LOOP
    INSERT INTO employee_dependent_attachments (
      dependent_code,
      employee_id,
      dependent_id,
      document_type,
      file_name,
      original_file_name,
      file_path,
      mime_type,
      file_size,
      uploaded_by,
      created_by,
      updated_by
    ) VALUES (
      v_dependent_code,
      p_employee_id,
      v_dependent_id,
      v_att->>'document_type',
      v_att->>'file_name',
      v_att->>'original_file_name',
      v_att->>'file_path',
      v_att->>'mime_type',
      (v_att->>'file_size')::bigint,
      auth.uid(),
      auth.uid(),
      auth.uid()
    )
    ON CONFLICT DO NOTHING;
  END LOOP;

  -- ── 6. Return success ──────────────────────────────────────────────────────
  RETURN jsonb_build_object(
    'ok',             true,
    'dependent_id',   v_dependent_id,
    'dependent_code', v_dependent_code
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION upsert_dependent(uuid, text, text, date, text, date, text, boolean, boolean, jsonb) IS
  'Add a new dependent (p_dependent_code = NULL) or amend an existing one '
  '(p_dependent_code = existing code). '
  'For new dependents: checks ''create'' permission. For amendments: checks ''edit'' permission. '
  'Workflow task holders and sent-back initiators bypass the standard permission check. '
  'Implements the Migration 288 effective-dating pattern: if the current open-ended row''s '
  'effective_from >= p_effective_from it is deleted (full replacement); otherwise it is '
  'closed at p_effective_from - 1 day. '
  'Returns {ok: true, dependent_id, dependent_code} on success. '
  'Returns {ok: false, error} on access denial or validation failure. '
  'Mig 289: initial creation.';

REVOKE ALL     ON FUNCTION upsert_dependent(uuid, text, text, date, text, date, text, boolean, boolean, jsonb) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION upsert_dependent(uuid, text, text, date, text, date, text, boolean, boolean, jsonb) TO authenticated;


-- =============================================================================
-- Part 13 — remove_dependent RPC
-- =============================================================================

CREATE OR REPLACE FUNCTION remove_dependent(
  p_employee_id     uuid,
  p_dependent_code  text,
  p_removal_date    date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_active_row  employee_dependents%ROWTYPE;
BEGIN
  -- ── 1. Access guard ────────────────────────────────────────────────────────
  -- Four paths (all use 'delete' permission):
  --   a) HR/admin with dependents.delete permission scoped to employee's target group
  --   b) ESS employee removing their own dependent with dependents.delete permission
  --   c) Approver holding a pending workflow task for this employee
  --   d) Initiator whose submission was sent back for clarification
  IF NOT (
    user_can('dependents', 'delete', p_employee_id)
    OR (
      p_employee_id = get_my_employee_id()
      AND has_permission('dependents.delete')
    )
    OR EXISTS (
      SELECT 1
      FROM   workflow_tasks wt
      JOIN   workflow_instances wi ON wi.id = wt.instance_id
      WHERE  wi.record_id   = p_employee_id
        AND  wt.assigned_to = auth.uid()
        AND  wt.status      = 'pending'
    )
    OR EXISTS (
      SELECT 1
      FROM   workflow_instances wi
      WHERE  wi.record_id    = p_employee_id
        AND  wi.submitted_by = auth.uid()
        AND  wi.status       = 'awaiting_clarification'
    )
  ) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Access denied: you do not have permission to remove dependents for this employee.');
  END IF;

  -- ── 2. Validate removal date ──────────────────────────────────────────────
  IF p_removal_date IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Removal date is required.');
  END IF;

  -- ── 3. Find the current active open-ended row ──────────────────────────────
  SELECT * INTO v_active_row
  FROM   employee_dependents
  WHERE  dependent_code = p_dependent_code
    AND  employee_id    = p_employee_id
    AND  is_active      = true
    AND  effective_to   = '9999-12-31'::date
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'No active dependent found.');
  END IF;

  -- ── 4. Check for orphaned future historical rows ──────────────────────────
  -- If any closed historical row (effective_to < '9999-12-31') begins on or after
  -- the removal date, the removal date is too early and would create a timeline gap.
  IF EXISTS (
    SELECT 1
    FROM   employee_dependents
    WHERE  dependent_code = p_dependent_code
      AND  employee_id    = p_employee_id
      AND  is_active      = true
      AND  effective_to   < '9999-12-31'::date
      AND  effective_from >= p_removal_date
  ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'Cannot remove: historical rows exist that begin on or after the removal date. Adjust the removal date or remove future records first.'
    );
  END IF;

  -- ── 5. Apply removal (mirror of Migration 288 pattern for dependents) ──────
  IF v_active_row.effective_from >= p_removal_date THEN
    -- The active row's entire period falls on or after the removal date.
    -- Mark it inactive in place — no need for a separate terminal row because
    -- this row itself becomes the terminal record.
    UPDATE employee_dependents
    SET    is_active  = false,
           inactive_at = now(),
           inactive_by = auth.uid(),
           updated_by  = auth.uid(),
           updated_at  = now()
    WHERE  id = v_active_row.id;

  ELSE
    -- The active row started before the removal date.
    -- Close the current row at removal_date - 1 day.
    UPDATE employee_dependents
    SET    effective_to = p_removal_date - interval '1 day',
           updated_by   = auth.uid(),
           updated_at   = now()
    WHERE  id = v_active_row.id;

    -- Insert a terminal row starting on the removal date.
    -- Copies all business fields from the current active row.
    INSERT INTO employee_dependents (
      dependent_code,
      employee_id,
      relationship_type,
      dependent_name,
      date_of_birth,
      gender,
      insurance_eligible,
      effective_from,
      effective_to,
      is_active,
      inactive_at,
      inactive_by,
      created_by,
      updated_by
    ) VALUES (
      v_active_row.dependent_code,
      v_active_row.employee_id,
      v_active_row.relationship_type,
      v_active_row.dependent_name,
      v_active_row.date_of_birth,
      v_active_row.gender,
      v_active_row.insurance_eligible,
      p_removal_date,
      '9999-12-31'::date,
      false,
      now(),
      auth.uid(),
      auth.uid(),
      auth.uid()
    );

  END IF;

  -- ── 6. Return success ──────────────────────────────────────────────────────
  RETURN jsonb_build_object('ok', true);

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('ok', false, 'error', SQLERRM);
END;
$$;

COMMENT ON FUNCTION remove_dependent(uuid, text, date) IS
  'Soft-delete (terminate) an active dependent. '
  'Creates a terminal record (is_active=false, effective_to=''9999-12-31'') to mark the '
  'end of the dependent''s coverage. If the active row''s effective_from >= p_removal_date, '
  'the row is marked inactive in place (no separate terminal row needed). '
  'Otherwise the current row is closed at p_removal_date - 1 day and a new terminal row '
  'is inserted from p_removal_date onwards, copying all business fields. '
  'Returns {ok: true} on success. Returns {ok: false, error} on failure. '
  'Mig 289: initial creation.';

REVOKE ALL     ON FUNCTION remove_dependent(uuid, text, date) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION remove_dependent(uuid, text, date) TO authenticated;


-- =============================================================================
-- Part 14 — Verification SELECTs
-- =============================================================================

-- Verify tables exist
SELECT
  table_name,
  table_type
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'employee_dependents',
    'employee_dependent_attachments'
  )
ORDER BY table_name;

-- Verify indexes
SELECT
  indexname,
  indexdef
FROM pg_indexes
WHERE tablename IN (
  'employee_dependents',
  'employee_dependent_attachments'
)
ORDER BY tablename, indexname;

-- Verify RLS policies
SELECT
  tablename,
  policyname,
  cmd,
  permissive
FROM pg_policies
WHERE tablename IN (
  'employee_dependents',
  'employee_dependent_attachments'
)
ORDER BY tablename, cmd;

-- Verify permissions seeded
SELECT code, name, sort_order
FROM permissions
WHERE code LIKE 'dependents.%'
ORDER BY sort_order;

-- Verify picklists seeded
SELECT pl.picklist_id, pl.name, COUNT(pv.id) AS value_count
FROM picklists pl
LEFT JOIN picklist_values pv ON pv.picklist_id = pl.id
WHERE pl.picklist_id IN (
  'DEPENDENT_RELATIONSHIP_TYPE',
  'DEPENDENT_DOCUMENT_TYPE'
)
GROUP BY pl.picklist_id, pl.name
ORDER BY pl.picklist_id;

-- Verify picklist values
SELECT pl.picklist_id, pv.ref_id, pv.value
FROM picklist_values pv
JOIN picklists pl ON pl.id = pv.picklist_id
WHERE pl.picklist_id IN (
  'DEPENDENT_RELATIONSHIP_TYPE',
  'DEPENDENT_DOCUMENT_TYPE'
)
ORDER BY pl.picklist_id, pv.ref_id;

-- Verify module code
SELECT code, label, description
FROM module_codes
WHERE code = 'profile_dependents';

-- Verify RPC functions exist
SELECT
  proname,
  prosecdef,
  pronargs
FROM pg_proc
WHERE proname IN (
  'fn_generate_dependent_code',
  'get_employee_dependents',
  'upsert_dependent',
  'remove_dependent'
)
ORDER BY proname;

-- =============================================================================
-- END OF MIGRATION 289
-- =============================================================================
